web:
  traceRouter: false      # if not specified, default is false
  traceAccess: false      # if not specified, default is false
  sessionTimeout: 900     # if not specified, default is 900
  maxUploadSize: 10485760 # if not specified, default is 10MB
  compressJs: true        # if not specified, default is true
  gzip: true              # if not specified, default is true
  defaultAllow: true      # if not specified, default is true
  accessRules: []         # if not specified, default is empty

scheduler:
  trace: false            # if not specified, default is false
  workers: 1              # Thread count, if not specified, default is 1
  jobs:
    job1:
      action: "myService::doJob"
      schedule:
        - "0/5 * * ? * * *"  # Override annotation setting
      enable: true        # if not specified, default is true

#db:
#  driver: "org.postgresql.Driver"
#  uri: "jdbc:postgresql://<IP_ADDRESS>:5432/<DB_NAME>"
#  user: "postgres"
#  password: "<PASSWORD>"
#  minConnectionsPerPartition: 5
#  maxConnectionsPerPartition: 20
#  partitionCount: 1
#  idleTestPeriod: 3 # in minutes
#  maxIdleAge: 30 # in minutes
#  disableConnectionTracking: false
#  trace: false
#
#mq:
#  broker: "activemq"      # or "amqp"
#  uri: "tcp://xxx.xxx.xxx.xxx:xxx"  # or amqp://xxx.xxx.xxx.xxx:xxx
#  user: "<USERNAME>"
#  password: "<PASSWORD>"
#  address: "default"      # queue or topic name
#  broadcast: false        # if false then address is a queue name otherwise is a topic name
#  trace: false
#
#mail:
#  trace: false            # if not specified, default is false
#  debug: false            # if not specified, default is false
#  auth: true              # if not specified, default is true
#  host: "xxx.xxx.xxx.xxx" # should provide it
#  port: 25                # if not specified, default is 25
#  user: "USER_NAME"       # REQUIRED, except 'auth' is false
#  password: "PASSWORD"    # REQUIRED, except 'auth' is false
#  secure: "no"            # if not specified, default is 'no', allow value is starttls, ssl, no
#  from: "someone@somewhere.com" # if not specified, default is null
#
#redis:
#  servers:
#    - "redis://[user:password]@<IP_ADDRESS>:6379/0"
#  maxTotal: 8
#  maxIdle: 8
#  minIdle: 0
#  connectionTimeout: 2000
#
#
#dbRouter:
#  post:_web_routine_name:
#     - "request_header:com.accenture.group.project.MyEntity"
#     - "request_body"
#     - "session"
#     - "response_header"
#     - "response_body"
