package com.github.thorqin.toolkit.utility;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by nuo.qin on 12/25/2014.
 */
public final class MimeUtils {
    public static final Map<String, String> MIME;
    /**
     * Unknown mime type
     */
    public static final String UNKNOWN_MIME = "application/octet-stream";
    static {
        MIME = new HashMap<>();
        MIME.put("323", "text/h323");
        MIME.put("acx", "application/internet-property-stream");
        MIME.put("ai", "application/postscript");
        MIME.put("aif", "audio/x-aiff");
        MIME.put("aifc", "audio/x-aiff");
        MIME.put("aiff", "audio/x-aiff");
        MIME.put("apk", "application/vnd.android.package-archive");
        MIME.put("asf", "video/x-ms-asf");
        MIME.put("asr", "video/x-ms-asf");
        MIME.put("asx", "video/x-ms-asf");
        MIME.put("au", "audio/basic");
        MIME.put("avi", "video/x-msvideo");
        MIME.put("axs", "application/olescript");
        MIME.put("bas", "text/plain");
        MIME.put("bcpio", "application/x-bcpio");
        MIME.put("bin", "application/octet-stream");
        MIME.put("bmp", "image/bmp");
        MIME.put("c", "text/plain");
        MIME.put("cat", "application/vnd.ms-pkiseccat");
        MIME.put("cc", "text/plain");
        MIME.put("cdf", "application/x-cdf");
        MIME.put("cer", "application/x-x509-ca-cert");
        MIME.put("class", "application/octet-stream");
        MIME.put("cpp", "text/plain");
        MIME.put("clp", "application/x-msclip");
        MIME.put("cmx", "image/x-cmx");
        MIME.put("cod", "image/cis-cod");
        MIME.put("cpio", "application/x-cpio");
        MIME.put("crd", "application/x-mscardfile");
        MIME.put("crl", "application/pkix-crl");
        MIME.put("crt", "application/x-x509-ca-cert");
        MIME.put("csh", "application/x-csh");
        MIME.put("cs", "text/plain");
        MIME.put("css", "text/css");
        MIME.put("dcr", "application/x-director");
        MIME.put("der", "application/x-x509-ca-cert");
        MIME.put("dir", "application/x-director");
        MIME.put("dll", "application/x-msdownload");
        MIME.put("dms", "application/octet-stream");
        MIME.put("doc", "application/vnd.ms-word");
        MIME.put("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        MIME.put("docm", "application/vnd.ms-word.document.macroEnabled.12");
        MIME.put("dot", "application/msword");
        MIME.put("dvi", "application/x-dvi");
        MIME.put("dxr", "application/x-director");
        MIME.put("emf", "image/x-emf");
        MIME.put("eps", "application/postscript");
        MIME.put("etx", "text/x-setext");
        MIME.put("evy", "application/envoy");
        MIME.put("exe", "application/octet-stream");
        MIME.put("fif", "application/fractals");
        MIME.put("flr", "x-world/x-vrml");
        MIME.put("gif", "image/gif");
        MIME.put("gtar", "application/x-gtar");
        MIME.put("gz", "application/x-gzip");
        MIME.put("h", "text/plain");
        MIME.put("hdf", "application/x-hdf");
        MIME.put("hlp", "application/winhlp");
        MIME.put("hqx", "application/mac-binhex40");
        MIME.put("hta", "application/hta");
        MIME.put("htc", "text/x-component");
        MIME.put("htm", "text/html");
        MIME.put("html", "text/html");
        MIME.put("htt", "text/webviewhtml");
        MIME.put("ico", "image/x-icon");
        MIME.put("ief", "image/ief");
        MIME.put("iii", "application/x-iphone");
        MIME.put("ins", "application/x-internet-signup");
        MIME.put("ipa", "application/octet-stream");
        MIME.put("isp", "application/x-internet-signup");
        MIME.put("jar", "application/java-archive");
        MIME.put("jfif", "image/pipeg");
        MIME.put("java", "text/plain");
        MIME.put("jpe", "image/jpeg");
        MIME.put("jpeg", "image/jpeg");
        MIME.put("jpg", "image/jpeg");
        MIME.put("js", "application/x-javascript");
        MIME.put("json", "application/json");
        MIME.put("latex", "application/x-latex");
        MIME.put("lha", "application/octet-stream");
        MIME.put("lsf", "video/x-la-asf");
        MIME.put("lsx", "video/x-la-asf");
        MIME.put("lzh", "application/octet-stream");
        MIME.put("m13", "application/x-msmediaview");
        MIME.put("m14", "application/x-msmediaview");
        MIME.put("m3u", "audio/x-mpegurl");
        MIME.put("man", "application/x-troff-man");
        MIME.put("mdb", "application/x-msaccess");
        MIME.put("me", "application/x-troff-me");
        MIME.put("mht", "message/rfc822");
        MIME.put("mhtml", "message/rfc822");
        MIME.put("mid", "audio/mid");
        MIME.put("mny", "application/x-msmoney");
        MIME.put("mov", "video/quicktime");
        MIME.put("movie", "video/x-sgi-movie");
        MIME.put("mp2", "video/mpeg");
        MIME.put("mp3", "audio/mpeg");
        MIME.put("mpa", "video/mpeg");
        MIME.put("mpe", "video/mpeg");
        MIME.put("mpeg", "video/mpeg");
        MIME.put("mpg", "video/mpeg");
        MIME.put("mpp", "application/vnd.ms-project");
        MIME.put("mpv2", "video/mpeg");
        MIME.put("ms", "application/x-troff-ms");
        MIME.put("mvb", "application/x-msmediaview");
        MIME.put("nws", "message/rfc822");
        MIME.put("oda", "application/oda");
        MIME.put("p10", "application/pkcs10");
        MIME.put("p12", "application/x-pkcs12");
        MIME.put("p7b", "application/x-pkcs7-certificates");
        MIME.put("p7c", "application/x-pkcs7-mime");
        MIME.put("p7m", "application/x-pkcs7-mime");
        MIME.put("p7r", "application/x-pkcs7-certreqresp");
        MIME.put("p7s", "application/x-pkcs7-signature");
        MIME.put("pbm", "image/x-portable-bitmap");
        MIME.put("pdf", "application/pdf");
        MIME.put("pfx", "application/x-pkcs12");
        MIME.put("pgm", "image/x-portable-graymap");
        MIME.put("pko", "application/ynd.ms-pkipko");
        MIME.put("plist", "text/xml");
        MIME.put("pma", "application/x-perfmon");
        MIME.put("pmc", "application/x-perfmon");
        MIME.put("pml", "application/x-perfmon");
        MIME.put("pmr", "application/x-perfmon");
        MIME.put("pmw", "application/x-perfmon");
        MIME.put("pnm", "image/x-portable-anymap");
        MIME.put("png", "image/png");
        MIME.put("pot,", "application/vnd.ms-powerpoint");
        MIME.put("ppm", "image/x-portable-pixmap");
        MIME.put("pps", "application/vnd.ms-powerpoint");
        MIME.put("ppt", "application/vnd.ms-powerpoint");
        MIME.put("pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
        MIME.put("ppat", "application/vnd.ms-powerpoint.presentation.macroEnabled.12");
        MIME.put("prf", "application/pics-rules");
        MIME.put("ps", "application/postscript");
        MIME.put("pub", "application/x-mspublisher");
        MIME.put("qt", "video/quicktime");
        MIME.put("ra", "audio/x-pn-realaudio");
        MIME.put("ram", "audio/x-pn-realaudio");
        MIME.put("ras", "image/x-cmu-raster");
        MIME.put("rgb", "image/x-rgb");
        MIME.put("rmi", "audio/mid http://www.dreamdu.com");
        MIME.put("roff", "application/x-troff");
        MIME.put("rtf", "application/rtf");
        MIME.put("rtx", "text/richtext");
        MIME.put("scd", "application/x-msschedule");
        MIME.put("sct", "text/scriptlet");
        MIME.put("setpay", "application/set-payment-initiation");
        MIME.put("setreg", "application/set-registration-initiation");
        MIME.put("sh", "application/x-sh");
        MIME.put("shar", "application/x-shar");
        MIME.put("sit", "application/x-stuffit");
        MIME.put("snd", "audio/basic");
        MIME.put("spc", "application/x-pkcs7-certificates");
        MIME.put("spl", "application/futuresplash");
        MIME.put("src", "application/x-wais-source");
        MIME.put("sst", "application/vnd.ms-pkicertstore");
        MIME.put("stl", "application/vnd.ms-pkistl");
        MIME.put("stm", "text/html");
        MIME.put("svg", "image/svg+xml");
        MIME.put("sv4cpio", "application/x-sv4cpio");
        MIME.put("sv4crc", "application/x-sv4crc");
        MIME.put("swf", "application/x-shockwave-flash");
        MIME.put("t", "application/x-troff");
        MIME.put("tar", "application/x-tar");
        MIME.put("tcl", "application/x-tcl");
        MIME.put("tex", "application/x-tex");
        MIME.put("texi", "application/x-texinfo");
        MIME.put("texinfo", "application/x-texinfo");
        MIME.put("tgz", "application/x-compressed");
        MIME.put("tif", "image/tiff");
        MIME.put("tiff", "image/tiff");
        MIME.put("tr", "application/x-troff");
        MIME.put("trm", "application/x-msterminal");
        MIME.put("tsv", "text/tab-separated-values");
        MIME.put("txt", "text/plain");
        MIME.put("uls", "text/iuls");
        MIME.put("ustar", "application/x-ustar");
        MIME.put("vcf", "text/x-vcard");
        MIME.put("vrml", "x-world/x-vrml");
        MIME.put("wav", "audio/x-wav");
        MIME.put("wcm", "application/vnd.ms-works");
        MIME.put("wdb", "application/vnd.ms-works");
        MIME.put("wks", "application/vnd.ms-works");
        MIME.put("wmf", "application/x-msmetafile");
        MIME.put("wps", "application/vnd.ms-works");
        MIME.put("wri", "application/x-mswrite");
        MIME.put("wrl", "x-world/x-vrml");
        MIME.put("wrz", "x-world/x-vrml");
        MIME.put("xaf", "x-world/x-vrml");
        MIME.put("xbm", "image/x-xbitmap");
        MIME.put("xhtml", "application/xhtml+xml");
        MIME.put("xla", "application/vnd.ms-excel");
        MIME.put("xlc", "application/vnd.ms-excel");
        MIME.put("xlm", "application/vnd.ms-excel");
        MIME.put("xls", "application/vnd.ms-excel");
        MIME.put("xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        MIME.put("xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12");
        MIME.put("xlt", "application/vnd.ms-excel");
        MIME.put("xlw", "application/vnd.ms-excel");
        MIME.put("xml", "text/xml");
        MIME.put("xof", "x-world/x-vrml");
        MIME.put("xpm", "image/x-xpixmap");
        MIME.put("xwd", "image/x-xwindowdump");
        MIME.put("z", "application/x-compress");
        MIME.put("zip", "application/zip");
    }

    /**
     * Get MIME type by pass full file name or file suffix name
     * @param suffix File name or file suffix name
     * @return MIME type
     */
    public static String getFileMime(String suffix) {
        int dotPos = suffix.lastIndexOf('.');
        if (dotPos >= 0)
            suffix = suffix.substring(dotPos+1);
        String mime = MIME.get(suffix.toLowerCase());
        if (mime == null)
            return UNKNOWN_MIME;
        else
            return mime;
    }
}
